### PR TITLE
[graphql] Allow fetching targeted ranges for any asset in backfill, fix links

### LINKED ISSUE #16953: "Could not find partitions for provided range" error when navigating to asset from backfill page
### Reproduction
- Launch a graph with two assets that have different PartitionsDefinitions:

```python
from dagster import asset, HourlyPartitionsDefinition, DailyPartitionsDefinition


hourly_partitions_def = HourlyPartitionsDefinition(start_date="2023-02-01-00:00")
daily_partitions_def = DailyPartitionsDefinition(start_date="2023-02-01")


@asset(partitions_def=hourly_partitions_def)
def asset1() -> None:
    ...


@asset(partitions_def=daily_partitions_def, deps=["asset1", "asset2"])
def asset2() -> None:
    ...
```

- Launch a backfill.
- Go the the page for that backfill
- Click on the link to the second asset
- Observe something like

image

### The issue

- We use the backfill's partition range to parameterize the URL that we use to filter partitions 
- That partition range corresponds to partitions that exist in the upstream asset, not the downstream asset

### Solution

Long term, we could do some partition mapping, but a shorter term solution might be to just not use filter by partition range in some situations.

### PR DESCRIPTION
**Pull request by bengotow**
## Summary & Motivation

Fixes #16953 

This PR adds a new resolver to PartitionBackfill that allows us to fetch the targeted partitions / ranges for any asset in a backfill, not just the root set. When you click one of the assets on this page, we fetch the ranges for that asset and take you to the asset detail page with that range selected.

When I added this, I also moved `rootAssetTargetedRanges` and `rootAssetTargetedPartitions` into a nested object and renamed partitions => partitionKeys -- I think this is nice since we always pass the two together and these same two keys are needed for the new resolver.

image

image

## How I Tested These Changes

Updated existing tests

### CODE REVIEW

File: js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx [hunk 1]
```diff
@@ -140,15 +146,25 @@ export const BackfillPage = () => {
...
 
-    const linkQuery = () => {
-      if (backfill.assetBackfillData?.rootAssetTargetedRanges?.length === 1) {
-        const ranges = backfill.assetBackfillData?.rootAssetTargetedRanges;
-        if (ranges?.length) {
-          const {start, end} = ranges[0]!;
-          return {default_range: `[${start}...${end}]`};
-        }
+    const onShowAssetDetails = async (assetKey: AssetKey) => {
+      const resp = await client.query<
```
Comment (salazarm) [inline js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx:150]: rather than using the client why not `useLazyQuery` ?

**Review by salazarm — APPROVED** [review]

**Review by clairelin135 — APPROVED** [review]
This looks great to me!

File: python_modules/dagster-graphql/dagster_graphql/schema/backfill.py [hunk 2]
```diff
@@ -115,17 +116,44 @@ class Meta:
...
 class GrapheneAssetBackfillData(graphene.ObjectType):
     class Meta:
         name = "AssetBackfillData"
 
     assetBackfillStatuses = non_null_list(
         "dagster_graphql.schema.partition_sets.GrapheneAssetBackfillStatus"
     )
-    rootAssetTargetedRanges = graphene.List(
-        graphene.NonNull("dagster_graphql.schema.partition_sets.GraphenePartitionKeyRange")
+    rootTargetedPartitions = graphene.NonNull(
```
Comment (clairelin135) [inline python_modules/dagster-graphql/dagster_graphql/schema/backfill.py:154]: it is possible for this to be null right? when the asset backfill data can't be deserialized

Comment (clairelin135) [reply python_modules/dagster-graphql/dagster_graphql/schema/backfill.py:154]: ah nevermind -- thought this was `PartitionBackfill`

File: js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx (hunk 1 above)
Comment (bengotow) [reply js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx:150]: Hmm - looked at some callsites and I think we mostly useLazyQuery in places where we want the result of the query stored in state + rendered... In this case we want something strictly imperative since we just use the result and redirect rather than rendering it. So i think this still makes sense...

File: js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx [hunk 3]
```diff
@@ -238,9 +251,9 @@ export const BackfillPage = () => {
                   <td>
                     <Box flex={{direction: 'row', justifyContent: 'space-between'}}>
                       <div>
-                        <Link to={assetDetailsPathForKey(asset.assetKey, linkQuery())}>
+                        <ButtonLink onClick={() => onShowAssetDetails(asset.assetKey)}>
```
[the remark this answers is not in the document]
Comment (bengotow) [reply js_modules/dagster-ui/packages/ui-core/src/instance/backfill/BackfillPage.tsx:254]: Yeah... I'm curious to see if anyone notices, but this means the links don't support cmd-click anymore. I was thinking we could pass through the event meta key state and use window.open, but we don't do that anywhere else and it seemed it might be overkill for now.
