### PR TITLE
[ui] Restore hover tooltip on run tags

### LINKED ISSUE #14355: Tags in run tables no longer expand on hover
### Dagster version

1.3.4

### What's the issue?

Sometime between 1.2.3 and 1.3.4, tags stopped expanding when hovered over in the runs table. As an example, the k8s tag below used to expand so the full value was visible when hovering over. Now, you need to copy the value to see it.
image

### What did you expect to happen?

I expect a way to see the full value within the table.

### How to reproduce?

_No response_

### Deployment type

Dagster Helm chart

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by hellendag**
## Summary & Motivation

Resolves #14355.

A recent change to `RunTag` led to the `data-tooltip` overlay no longer working. Restore this by adding an optional `tooltipText` that allows setting a tooltipable value when the tag child is not a string.

## How I Tested These Changes

Create a run with a long tag, verify that the tag renders correctly when truncated and when hovered.

Default:

Screenshot 2023-05-30 at 1 40 29 PM

Hovered, with tooltip:

Screenshot 2023-05-30 at 1 40 24 PM

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #14532** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/14532" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/14532?utm_source=stack-comment).

**Review by salazarm — APPROVED** [review]

File: js_modules/dagit/packages/ui/src/components/BaseTag.tsx [hunk 1]
```diff
@@ -35,13 +36,14 @@ export const BaseTag = (props: Props) => {
...
     label,
+    tooltipText,
   } = props;
   return (
     <StyledTag $fillColor={fillColor} $interactive={interactive} $textColor={textColor}>
       {icon || null}
       {label !== undefined && label !== null ? (
         <span
-          data-tooltip={typeof label === 'string' ? label : undefined}
+          data-tooltip={typeof label === 'string' ? label : tooltipText || null}
```
Comment (salazarm) [inline js_modules/dagit/packages/ui/src/components/BaseTag.tsx:46]: do we need `|| null` here?

**Review by salazarm — APPROVED** [review]

**Review by bengotow — APPROVED** [review]
