### PR TITLE
[dagit] Add bulk re-execution dialog to Runs page

### LINKED ISSUE #6158: multiple re-execution of failures from Runs page
## Use Case

Re-execution of failures is slow and inefficient as it is only possible to re-execute failed executions on an individual basis.

From the Runs page the steps to re-execute are as follows:

1. Navigate to Runs page.
2. Apply Filter of staus:FAILURE.
3. Select Re-excution option for one of the failures; this takes you to the instance runs page.
4. Navigate back to the Runs page and repeat the previous 2 steps for all failures.

The good thing about re-executing from the Runs page is that this re-executes the same job instance so once successful this is reflected on the Runs page.  Furthermore, for back-fills re-execution from the Runs page is also reflected in the back-fill status so when a back-fill failure is re-executed successfully the back-fill Succeeded status is incremented by 1 and the Failed status is decremented by 1.

There is an alternative to re-execute failed execution from the Partitions Run Matrix however the behaviour here is completely different as this launches a new backfill with new job run instances so the original failures still appear on the Runs page and for backfills the original backfill status is not updated.  Furthermore, the partitions page is very slow and only works at an individual job level so for failures across many jobs, the process would need to be repeated for each job.

## Ideas of Implementation

A better solution would be to be able to trigger multiple re-executions at once from the Runs page which would set the selected runs back to NOT_STARTED status so that they get re-queued and re-executed by Dagster.  The only options currently available when multiple run instances are selected are Terminate and Delete so we would need a new Re-execution option.

## Additional Info

---
#### Message from the maintainers:
Excited about this feature? Give it a :thumbsup:. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by hellendag**
## Summary

Resolves #6158, or at least proposes to. It's probably worth talking through whether this is the change we want.

Introduce another bulk operation option on the Runs page: re-execute all. This uses a very similar UI to terminate-all and delete-all bulk operations on this page.

- The user is presented with a dialog asking to confirm the re-execution.
- If confirmed, re-execution is performed using the run config from the original run. There is no customization or step selection, because I'm not sure how we could even do that here without making the UI super complex.
- Upon confirmation, send a series of mutations to perform re-executions. Show a progress bar as the runs are requested.
- Upon completion, show errors in a list, and show the number of confirmed re-execution requests.

Screenshots below.

## Test Plan

Jest test. Run Dagit, re-execute runs in bulk, or at least attempt to do so. Verify that some runs re-execute correctly, and tha some have workspace mismatch errors because the relevant jobs are not loaded in my current workspace.

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #7451** <a href="https://app.graphite.dev/github/pr/dagster-io/dagster/7451" target="_blank">Graphite</a>  (this PR)

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/dagster-io/dagster/7451?utm_source=stack-comment).

**Comment by hellendag** [comment]
Screen Shot 2022-04-14 at 12 25 28 PM

Screen Shot 2022-04-14 at 12 25 35 PM

**Comment by sryza** [comment]
This looks pretty reasonable to me

File: js_modules/dagit/packages/core/src/runs/RunTable.tsx [hunk 1]
```diff
@@ -148,6 +148,7 @@ export const RUN_TABLE_RUN_FRAGMENT = gql`
     canTerminate
     mode
     rootRunId
+    runConfigYaml
```
Comment (prha) [inline js_modules/dagit/packages/core/src/runs/RunTable.tsx:151]: I think this can be expensive, depending on the size of the config document.  Is there a way to defer fetching until there's some intent to re-execute?

Comment (bengotow) [reply js_modules/dagit/packages/core/src/runs/RunTable.tsx:151]: Ahh yeah if IRC we recently had a customer say their run config was like 100kb of YAML - I know our pagination limits the impact to just 25 runs, but since this page auto-refreshes it might add up over time. Probably worth deferring 😬

File: js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx [hunk 2]
```diff
@@ -0,0 +1,343 @@
...
+export const ReexecutionDialog = (props: Props) => {
+  const {isOpen, onClose, onComplete, selectedRuns} = props;
+
+  // Freeze the selected IDs, since the list may change as runs continue processing and
+  // re-executing. We want to preserve the list we're given.
+  const frozenRuns = React.useRef<SelectedRuns>(selectedRuns);
+
+  const [state, dispatch] = React.useReducer(
+    reexecutionDialogReducer,
+    frozenRuns.current,
```
Comment (bengotow) [inline js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx:133]: It doesn't seem like any of the state transitions modify this value so just using `frozenRuns.current` might be better? It's a little tricky that some of the code on 137-147 uses the state version and some uses the ref version.

File: js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx [hunk 3]
```diff
@@ -0,0 +1,343 @@
...
+    }
+  }, [isOpen]);
+
+  // If the dialog is not open, update the ref so that the frozen list will be entered
+  // into state the next time the dialog opens.
+  React.useEffect(() => {
+    if (!isOpen) {
+      frozenRuns.current = selectedRuns;
+    }
+  }, [isOpen, selectedRuns]);
```
Comment (bengotow) [inline js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx:154]: (Looks good to me but this ref + effect might be another argument for the "detatched dialogs" pitch ;-) )

**Review by bengotow — APPROVED** [review]
This looks great! Accumulating the success / failure events into state with useReducer is a super clean way to implement this 🙌

**Comment by hellendag** [comment]
Discussed with @prha a bit. What I'd really like to have here is a mutation that just allows me to provide a run ID, without requiring me to construct execution parameters. Since I'm querying for config yaml just so that I can pass it back through as an arg, it would be nice not to have to do that extra work. (Same thing for digging up repo matches in the loaded workspace. The backend should be able to handle this.)

So I'll hold off on merging this for the next couple days, and then hopefully we'll have a nice clean mutation to use, and a lot less fetching/manipulating being done in JS.

File: js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx (hunk 2 above)
Comment (hellendag) [reply js_modules/dagit/packages/core/src/runs/ReexecutionDialog.tsx:133]: It updates when the dialog transitions from closed to open. We could update the ref when this happens, but we'd also want to re-render the dialog with the new list of runs, so IIRC that's why it's using a `dispatch`.

File: js_modules/dagit/packages/core/src/runs/RunActionsMenu.tsx [hunk 4]
```diff
@@ -257,6 +264,9 @@ export const RunBulkActionsMenu: React.FC<{
   const selectedIDs = selected.map((run) => run.runId);
   const deletionMap = selected.reduce((accum, run) => ({...accum, [run.id]: run.canTerminate}), {});
 
+  const failedRuns = selected.filter((r) => failedStatuses.has(r?.status));
+  const reexecutionMap = failedRuns.reduce((accum, run) => ({...accum, [run.id]: run}), {});
+
```
Comment (hellendag) [inline js_modules/dagit/packages/core/src/runs/RunActionsMenu.tsx:269]: For now, just support re-execution from failure. `ALL_OPS` will be added later. cc @johannkm

**Comment by hellendag** [comment]
Screen Shot 2022-04-22 at 4 54 09 PM
Screen Shot 2022-04-22 at 4 54 15 PM

**Review by prha — APPROVED** [review]
