### PR TITLE
fix(dagit): use repository name in url path when linking search items

### LINKED ISSUE #5498: Dagit search job/pipeline name redirects to unknown repository error
### Issue from the [Dagster Slack](https://join.slack.com/t/dagster/shared_invite/enQtNjEyNjkzNTA2OTkzLTI0MzdlNjU0ODVhZjQyOTMyMGM1ZDUwZDQ1YjJmYjI3YzExZGViMDI1ZDlkNTY5OThmYWVlOWM1MWVjN2I3NjU)

Dagit search job/pipeline name redirects to unknown repository error

This issue was generated from the slack conversation at: https://dagster.slack.com/archives/C01U954MEER/p1635837872310700?thread_ts=1635837872.310700&cid=C01U954MEER

Conversation excerpt:

```
U01PJEQJEKF: got a `search redirect` bug I think
steps:
1. press `/` to search for a pipeline name
2. it redirects me to `<http://localhost:3000/workspace/crm@repos.py/jobs/crm>` --&gt; produces `Unknown repository` error
but the actual path is `<http://localhost:3000/workspace/baania_repository@repos.py/jobs/crm>`

this is my workspace config:
UULA0R2LV: Hi Max, thanks for reporting. This seems a bug.
UULA0R2LV: <@U018K0G2Y85> issue Dagit search job/pipeline name redirects to unknown repository error
```

---

#### Message from the maintainers:

Are you looking for the same documentation content? Give it a :thumbsup:. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by rexledesma**
## Summary
Resolves https://github.com/dagster-io/dagster/issues/5498

## Test Plan
check search locally, see links work.

### CODE REVIEW

**Comment by rexledesma** [comment]
Current dependencies on/for this PR:
* master
  * **PR #5507**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh) and will continue to be automatically updated while this PR remains open.

File: js_modules/dagit/packages/core/src/search/useRepoSearch.tsx [hunk 1]
```diff
@@ -38,9 +38,9 @@ const bootstrapDataToSearchResults = (data?: SearchBootstrapQuery) => {
...
       ...accum,
       ...repos.reduce((inner, repo) => {
-        const {name, partitionSets, pipelines, schedules, sensors} = repo;
+        const {name: repoName, partitionSets, pipelines, schedules, sensors} = repo;
         const {name: locationName} = repoLocation;
-        const repoPath = buildRepoPath(name, locationName);
+        const repoPath = buildRepoPath(repoName, locationName);
 
         const allPipelinesAndJobs = pipelines.reduce((flat, pipelineOrJob) => {
           const {name, isJob} = pipelineOrJob;
```
Comment (gibsondan) [inline js_modules/dagit/packages/core/src/search/useRepoSearch.tsx:46]: ah oops! Surprised this isn't some kind of JS warning

**Review by gibsondan — APPROVED** [review]
