### PR TITLE
[ui] Replace broken “Open in launchpad” links for asset jobs

### LINKED ISSUE #16639: Asset job "Open in launchpad" takes you to the playground page with no way to specify asset selection
### Dagster version

1.4.14

### What's the issue?

While investigating #16613, I was able to reach the old playground page for an asset job without an asset selection by clicking the Open in Launchpad button on an existing asset job run.  This option is also in a dropdown menu on the list page. This:

1) opens the /playground launchpad without the op/asset/check selection of the current run. You can use the query selector syntax to specify an op selection but not an asset or check selection.

2) goes to the /playground page which isn't supposed to exist for asset jobs

This button /might/ be ok for custom asset jobs but should definitely not exist in it's current form for __ASSET_JOB_0. The button doesn't copy the current run's config or tags or anything at all, so it really offers nothing that going to asset graph page and clicking "Materialize" doesn't offer.

### What did you expect to happen?

I expected that clicking Open in Launchpad from a run would take me to the exact launchpad view that I saw before I launched that run. I think we should try to make it do that if we can, but I'm not sure to what extent we can pass in all the original context.

### How to reproduce?

_No response_

### Deployment type

None

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by bengotow**
## Summary & Motivation

Fixes #16639 

The top right of the Run page has always shown an "Open in Launchpad" button. There are two big problems:

- The launchpad / playground page does not exist for asset jobs and this opens it anyway
- The launchpad for a hidden asset job launches the entire asset graph, not the asset selection of the run you're viewing

This PR replaces this button (and the corresponding RunActionsMenu item) with three different actions based on the job type:

- For op jobs, it remains "Open in Launchpad" (Launchpad is capitalized, which is a bit odd, but we do it consistently everywhere as if it were a proper noun, so I left it that way!)

- For hidden asset jobs, it is "View asset graph" and links to the global graph view of the subset of assets you launched

- For proper asset jobs, it is "View job" and links to the main graph page of the job (since asset jobs have no launchpad)
 

image

## How I Tested These Changes

I tested the different disabled states (it is disabled for op jobs if you do not have re-execute permission) by manually inserting true/false values in the data to verify the logic was correct. Also tested with the three different kinds of jobs above and verified the tooltips + run actions menu work. There is also a jest test for this and I verified it still passes.

### CODE REVIEW

File: js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx [hunk 1]
```diff
@@ -73,27 +72,26 @@ export const RunConfigDialog = ({run, isJob}: {run: RunFragment; isJob: boolean}
...
       <Group direction="row" spacing={8}>
-        {run.hasReExecutePermission ? (
-          <AnchorButton icon={<Icon name="edit" />} to={jobPath}>
-            Open in Launchpad
-          </AnchorButton>
-        ) : (
-          <Tooltip content={NO_LAUNCH_PERMISSION_MESSAGE} useDisabledButtonTooltipFix>
+        {jobLink.disabledReason ? (
+          <Tooltip content={jobLink.disabledReason} useDisabledButtonTooltipFix>
             <Button icon={<Icon name="edit" />} disabled>
```
Comment (hellendag) [inline js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx:87]: Worth adjusting the `icon` here, since the action is slightly different in each case now?

**Review by hellendag — APPROVED** [review]

File: js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx (hunk 1 above)
Comment (bengotow) [reply js_modules/dagster-ui/packages/ui-core/src/runs/RunConfigDialog.tsx]: Ahh yeah I think that's a good idea 👍
