### PR TITLE
[ui] Show “Observe” instead of “Materialize” in context menus for source assets

### LINKED ISSUE #20459: Source asset UI button shows `materialize` instead of `observe`
### Dagster version

1.6.9

### What's the issue?

Currently when you right click on a source in the global asset lineage left pane it says `materialize` instead of `observe`.

image

This is super counter intuitive because when you click materialize you get an error:

image

### What did you expect to happen?

_No response_

### How to reproduce?

_No response_

### Deployment type

Dagster Helm chart

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by bengotow**
Fixes #20459

## Summary & Motivation

It turns out there's a lot of inconsistency in the context menus + asset list menus:

- We now show the same Materialize or Observe menu item in the context menus and the asset catalog's list action menus.

- For executable source assets, "Observe" is shown and does the same thing that clicking "Observe sources" does on the graph via a new "useObserveAction" hook that matches "useMaterializeAction"

- The menus all observe both `canSeeMaterializeAction` and `asset.hasMaterializePermission` and use the same messaging for disabled states

## How I Tested These Changes

Just manually ran through these cases with materializable / observable assets

### CODE REVIEW

**Review by salazarm — APPROVED** [review]

File: js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx [hunk 1]
```diff
@@ -99,7 +86,81 @@ export const AssetActionMenu = (props: Props) => {
...
+  } = useContext(CloudOSSContext);
+
+  const materialize = useMaterializationAction();
+  const observe = useObserveAction();
+
+  if (!canSeeMaterializeAction) {
+    return {executeItem: null, launchpadElement: null};
+  }
+
+  if (definition?.isExecutable && definition.isSource && definition.hasMaterializePermission) {
```
Comment (salazarm) [inline js_modules/dagster-ui/packages/ui-core/src/assets/AssetActionMenu.tsx:116]: canSeeMaterializeAction probably applies to observations too imo
