### PR TITLE
[dagit] Fix Terminate button on Run page

### LINKED ISSUE #6160: [dagit] terminate button appears unexpectedly
### Issue from the [Dagster Slack](https://join.slack.com/t/dagster/shared_invite/enQtNjEyNjkzNTA2OTkzLTI0MzdlNjU0ODVhZjQyOTMyMGM1ZDUwZDQ1YjJmYjI3YzExZGViMDI1ZDlkNTY5OThmYWVlOWM1MWVjN2I3NjU)

This issue was generated from the slack conversation at: https://dagster.slack.com/archives/C01U954MEER/p1641618102110200?thread_ts=1641618102.110200&cid=C01U954MEER

---

### Conversation excerpt

U02LBCBDMS7: Hi there - just trying out the latest release (0.13.13)

When I execute a run via "Launchpad &gt; Launch Run", after the run completes (marked success), the "Terminate" button shows up suddenly in the top right. Is this intended? (Not gonna lie, maybe I just didn't notice that this was a thing in previous releases. If this is intended, my bad.)

Screenie attached (ran locally)
UH3RM70A2: <@U018K0G2Y85> issue [dagit] terminate button appears unexpectedly

---

#### Message from the maintainers:

Do you care about this too? Give it a :thumbsup:. We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by hellendag**
## Summary

Resolves #6160.

I accidentally flipped a boolean for the run Termination button.

Also cleaning up some dependency issues that showed up during testing, namely a repeated installation of `styled-components` in the yarn workspace that needed to be ironed out. I might need to do another pass through the deps in the workspace tree to make sure there aren't anymore of these.

## Test Plan

Run Dagit, view an in-progress run. Verify that the termination button is present and functional. View a completed run, verify that it is not.

### CODE REVIEW

**Comment by hellendag** [comment]
Current dependencies on/for this PR:
* master
  * **PR #6191**  (this PR)

This comment was auto-generated by [Graphite](https://graphite.dev?utm_source=gh).

File: js_modules/dagit/packages/core/src/runs/RunActionButtons.tsx [hunk 1]
```diff
@@ -234,7 +234,7 @@ export const RunActionButtons: React.FC<RunActionButtonsProps> = (props) => {
           disabled={pipelineError?.disabled || !canLaunchPipelineReexecution}
         />
       </Box>
-      <CancelRunButton run={run} isFinalStatus={!doneStatuses.has(run.status)} />
+      <CancelRunButton run={run} isFinalStatus={canRunAllSteps(run)} />
```
Comment (hellendag) [inline js_modules/dagit/packages/core/src/runs/RunActionButtons.tsx:237]: Here's the bugfix.

**Comment by hellendag** [comment]
Yep, a jest test would work well here. I'll add one.
