### PR TITLE
[ui] More performant line numbers rendering in raw log content

### LINKED ISSUE #13026: A lot of tqdm stdout freezes Dagit
### Dagster version

1.2.2

### What's the issue?

I'm training a DL model with pytorch-lighthing, which has a tqdm progress bar enabled by default. 
After a while, Dagit becomes very unresponsive.

### What did you expect to happen?

_No response_

### How to reproduce?

Run a long job with a tqdm bar

### Deployment type

Local

### Deployment details

_No response_

### Additional information

_No response_

### Message from the maintainers

Impacted by this issue? Give it a 👍! We factor engagement into prioritization.

### PR DESCRIPTION
**Pull request by bengotow**
## Summary & Motivation

Fixes #13026

Investigation into #13026 turned this up -- we set a log limit at ~5MB, but a 5MB log can still have 200k+ lines if the user is logging short bits of text.

We were previously rendering 200k divs for 200k line numbers. It'd obviously be ideal to virtualize this whole thing, but since we use `anser` to render the raw text content and it does some interesting processing of line control characters, I'm not sure that we can just "cut" the text into lines and render the last N lines. Virtualization here might be more complicated.

In the meantime, I switched the implementation of the line numbers so it takes less time per render. Instead of re-processing 200k React children each render, I track the previous # of lines, and append a div with the new #s that are needed (and blow it all away if the line number count has gone down.) I think it's worth doing this outside React because we know there is exactly one case (appending new numbers) that covers 99.9% of the updates.

The remaining stutter on this page is caused by forced sync layout required by the `scrollToBottom` behavior, which sets scrollTop in a componentDidUpdate. I'm not sure how to avoid that, but it'd be nice if we could.

## How I Tested These Changes

I tested these changes manually and used the sample in the issue above to spam stdout + stderr.

image

image

### CODE REVIEW

File: js_modules/dagster-ui/packages/ui-core/src/runs/RawLogContent.tsx [hunk 1]
```diff
@@ -253,18 +253,35 @@ class ScrollContainer extends React.Component<IScrollContainerProps> {
...
+    if (count < lastCount.current) {
+      containerEl.textContent = '';
+      lastCount.current = 0;
+    }
+    const div = document.createElement('div');
+    const addedCount = count - lastCount.current;
+    div.textContent = Array.from(Array(addedCount), (_, i) =>
+      String(lastCount.current + i + 1),
+    ).join('\n');
+    containerEl.appendChild(div);
```
Comment (hellendag) [inline js_modules/dagster-ui/packages/ui-core/src/runs/RawLogContent.tsx:280]: Could we end up with the line numbers misaligned with respect to the log lines? (Of course I don't know whether that's already a problem...)

**Review by hellendag — COMMENTED** [review]
How difficult would it be to just go ahead and virtualize this?

**Comment by salazarm** [comment]
> The remaining stutter on this page is caused by forced sync layout required by the scrollToBottom behavior, which sets scrollTop in a componentDidUpdate. 

Did you try wrapping the logic that sets `scrollTop` in a requestAnimationFrame? If so then likely there are multiple rounds of DOM read -> DOM write -> DOM read -> DOM write. If that's the case we should implement a queryDOM and mutateDOM function that batches reads / writes respectively to allow the app to have the minimum number of these cycles and avoid unnecessary forced layouts.

File: js_modules/dagster-ui/packages/ui-core/src/runs/RawLogContent.tsx (hunk 1 above)
Comment (bengotow) [reply js_modules/dagster-ui/packages/ui-core/src/runs/RawLogContent.tsx:280]: Yeah I'm actually really surprised this was working at all -- it does seem to work correctly but only because we don't do text wrapping on the raw logs, and each line has a consistent height

**Comment by bengotow** [comment]
Hmm, agree virtualizing this would be ideal. I don't think it'd be too hard because each line really is just Xpx high (there is no text wrapping). The fact that some lines replace the prev line using control characters means we still have to run the ANSI logic on them, but that's not bad. 

I think the biggest issue is that right now you can Cmd-F and search the raw logs, and if we virtualize them we probably need to replicate that and select-all for it not to be annoying. I'd vote we do this 30min version first and see if anyone comes up with a case where <5MB of logs (the limit) is still pushing it too hard.

re:  scrollTop in a requestAnimationFrame -- that's a good idea! I tried it out and it does look better, will update this. It looks like we still hit a forced reflow in a slightly different spot (`scrollToBottomObserver`?) The log stream is debounced somewhere upstream of the UI though so it's only one update every couple seconds.

image

I think if we want to work on perf on this page more, we may want to revisit not running constant animation frames for the Gantt UI once the run has been going for >10min and there are no perceptible changes between frames. I think we rm'd the code that lowered the framerate at some point because it was too complicated.

**Comment by bengotow** [comment]
Fixes https://github.com/dagster-io/dagster/issues/13026

**Review by salazarm — APPROVED** [review]
thanks for digging in!
